/* libusb/config.h.  Generated by hand for Android. */

#ifndef CONFIG_H
#define CONFIG_H

/* Enable backend support for Linux usbfs */
#define OS_LINUX 1

/* Use POSIX threads */
#define THREADS_POSIX 1

/* Define to 1 if you have the <sys/time.h> header file. */
#define HAVE_SYS_TIME_H 1

/* Define to 1 if you have the <nfnetlink.h> header file. */
/* #undef HAVE_NFNETLINK_H */

/* Enable polling on eventfd */
#define USBI_TIMERFD_AVAILABLE 1

/* Disable netlink support for Android to avoid socket creation errors */
#undef HAVE_LINUX_NETLINK

/* Default to logs enabled */
#define ENABLE_LOGGING 1
#define LOG_LEVEL_INFO 1

/* Version */
#define PACKAGE_VERSION "1.0.26"

/* Found in libusb/libusbi.h, needs definition if not using autotools */
#ifndef PRINTF_FORMAT
#if defined(__GNUC__) || defined(__clang__)
#define PRINTF_FORMAT(a, b) __attribute__ ((format (printf, a, b)))
#else
#define PRINTF_FORMAT(a, b)
#endif
#endif

/* libusb expects this to be defined for POSIX platforms */
#define PLATFORM_POSIX 1

/* Visibility attribute support */
#if defined(__GNUC__) || defined(__clang__)
#define DEFAULT_VISIBILITY __attribute__((visibility("default")))
#else
#define DEFAULT_VISIBILITY
#endif

/* Real-time clock support */
#define HAVE_CLOCK_GETTIME 1

#endif
